/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes
const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Create and export the route tree
export interface FileRoutesByPath {
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof IndexImport;
    parentRoute: typeof rootRoute;
  };
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
}

export const routeTree = rootRoute
  ._addFileChildren([IndexRoute])
  ._addFileTypes<FileRoutesByPath>();
